name: update

on:
  schedule:
  #        ┌───────────── minute (0 - 59)
  #        │ ┌───────────── hour (0 - 23)
  #        │ │ ┌───────────── day of the month (1 - 31)
  #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #        │ │ │ │ │
    - cron: "0/5 * * * *"

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependency
        run: pip install aiohttp
      - name: Set github user
        run: git config user.name "user-11150"
      - name: Set github email
        run: git config user.email 3584434540@qq.com
      - name: Set github remote
        run: git remote set-url origin https://${TOKEN}@github.com/user-11150/Top-100-of-pypi-big-projects
        env:
          TOKEN: ${{secrets.TOKEN}}
      - name: Update
        run: python main.py
