name: docs

on:
  schedule:
  #        ┌───────────── minute (0 - 59)
  #        │ ┌───────────── hour (0 - 23)
  #        │ │ ┌───────────── day of the month (1 - 31)
  #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #        │ │ │ │ │
  - cron: "* * * * *"

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependency
        run: pip install 
      - name: Set github user
        run: git config user.name "user-11150"
      - name: Set github remote
        run: git remote set-url origin https://${TOKEN}@github.com/user-11150/Top-100-of-pypi-big-projects
        env:
          TOKEN: secrets.TOKEN
      - name: Update
        run: python main.py
